export type UserT = {
  id: string;
  userName: string;
  firstName: string;
  lastName: string;
  email: string | null;
  isActive: boolean;
  createDate: string;
  middleName: string | null;
  gender: string | null;
  title: string | null;
  info: string | null;
  emailConfirmed: boolean;
  phoneNumberConfirmed: boolean;
  phoneNumber: string;
  imageUrl: string;
  thumbnail: string | null;
  companyName: string | null;
  companyNumber: string | null;
  code: string;
  userType: string | null;
  codeType: number;
  companyId: string | null;
  jsonExt: string | null;
  vatNumber: string | null;
  representative: string;
  sheba: string | null;
  bankname: string | null;
  birthdate: string | null;
  codeMeli: string | null;
  representativeBy: string;
  representativeDate: string;
  blueUser: string | null;
  blueUSerActiveDate: string | null;
  issue: string | null;
  rolesRequests: string | null;
  instagram: string | null;
  facebook: string | null;
  linkedIn: string | null;
  twitter: string | null;
  gitHub: string | null;
  skype: string | null;
  telegram: string | null;
  whatsApp: string | null;
  follower: number;
  following: number;
};